### ISSUE TITLE
Feature Request: Check for possible checkout plays different "you require ...." audio file

### ISSUE THREAD

**Issue by viperman3** [lbormann/autodarts-caller#1]
Is it possible to add a feature request where audio files with the following prefix are played for possible checkout <= 170

yr_2-yr_170.{wav | mp3} for possible checkout audio files
and
0-180.{wav | mp3} for game score

something like this:
        # Check for possible checkout
        elif POSSIBLE_CHECKOUT_CALL and m['player'] == currentPlayerIndex and m['gameScores'][currentPlayerIndex] <= 170 and turns != None and turns['throws'] == None:
            play_sound_effect('yr_' + str(m['gameScores'][currentPlayerIndex]))
            printv('Match: Checkout possible')

thank you

**Comment by lbormann** [comment]
Added in todos; though for naming I would prefer "pc_2-pc_170.{wav | mp3}" - pc = possible checkout
