### ISSUE TITLE
Setup caller failed!

### ISSUE THREAD

**Issue by screechyboy79** [lbormann/autodarts-caller#11]
Process is autodarts-caller-arm64
##########################################
       WELCOME TO AUTODARTS-CALLER
##########################################
VERSION: 2.8.5
RUNNING OS: Linux | posix | 6.1.0-rpi8-rpi-2712
SUPPORTED GAME-VARIANTS: X01 Cricket Random Checkout ATC
DONATION: bitcoin:bc1q8dcva098rrrq2uqhv38rj5hayzrqywhudvrmxa
Downloader: filter for language: 1
20 voice-pack(s) found.
en-us-stephen-male-v4
en-us-kendra-female-v4
en-us-stephen-male-v4
en-us-matthew-male
en-us-wavenet-j-male-v4
en-us-wavenet-e-female-v4
en-us-joanna-female-v4
en-us-joey-male-v4
en-us-danielle-female
en-us-wavenet-a-male-v4
en-us-ivy-female-v4
en-us-kimberly-female
en-us-wavenet-f-female-v4
en-us-kevin-male
en-us-ruth-female
en-us-gregory-male
en-us-wavenet-i-male-v4
en-us-wavenet-g-female-v4
en-us-wavenet-h-female-v4
en-us-salli-female
**Setup caller failed!**

**Comment by screechyboy79** [comment]
I did a fresh install it worked temporarily but after a reboot I get the same error message again.

**Comment by lbormann** [comment]
try this: https://discord.com/channels/802528604067201055/1146375876787843174/1212037792096591944
if your problem does not disappear, contact me on discord. Also enable DEBUG with DEB 1
