### ISSUE TITLE
No sound playing

### ISSUE THREAD

**Issue by BrentGeentjens** [lbormann/autodarts-caller#13]
Hello,

i've installed autodarts on a raspberry pi 4B this is working great.
I've tried to install autodarts-caller, if I Ssh into the pi it says its running, when i start a match i see the the service running and saying match on but when i log into autodarts on my tablet it's not playing the sounds. How do i fix this ?

Kind regards 
Brent Geentjens

**Comment by lbormann** [comment]
Hi, please ask in DC.
