### ISSUE TITLE
Fallback to actual tripple/double value in case tripple / double file is missing

### ISSUE THREAD

**Issue by shaxqt** [lbormann/autodarts-caller#14]
https://github.com/lbormann/autodarts-caller/blob/34bff17e497da069313b6c903fc69c71817a8299/autodarts-caller.py#L1365

Moin, ich hätte da einen Vorschlag bzw. einen Wunsch :) 
Könnte man hier nicht checken ob "type" gespielt werden konnte und falls nicht (weil man vllt n caller hat der dafür keine sounds hat)
könnte man alternativ doch den type (double / tripple) * single field value nehmen und die Zahl callen. Also die 60 statt tripple + 20 beispielsweise.

Hab da irgendwo im Netz so einen[ Russ Bray caller](https://www.dartn-forum.de/thread/129-russ-bray-sounds-f%C3%BCr-dartpro-software/?postID=473437#post473437) gefunden und der hat nur die Zahlen 1-180 👀

Aber ich dachte das wäre vllt auch für andere Leute nützlich, sonst wird halt immer 20 gecallt, egal ob doppel oder tripple 🤔 

Cooles Projekt haste hier erstellt übrigens, ohne den Caller macht autodarts nicht mal halb so viel Spaß :)

Falls du dazu Fragen hast, bin auch im Discord 👍

**Comment by michvllni** [comment]
Find ich keine schlechte Alternative.

Alternativ: Gibt ja so einige apps im play store, die russ als caller drin haben...wenn .apk Dateien doch nur .zip Files wären, aus denen man sich mit 7 Zip die Dateien einfach rauskopieren könnte... ;)

**Comment by shaxqt** [comment]
Guter Tipp, ich könnt mir auch die ganzen Sound Files kopieren und die 60 umbennen in t20.
Aber ich würd es auch cool finden, wenn die caller generell die Summe des Feldes callen anstatt "tripple" und "Double". Weiß nicht ob ich da der einzige mit der Meinung bin :D
Aber ich schau Ma mach apks mit callern ;)

**Comment by lbormann** [comment]
> Guter Tipp, ich könnt mir auch die ganzen Sound Files kopieren und die 60 umbennen in t20. Aber ich würd es auch cool finden, wenn die caller generell die Summe des Feldes callen anstatt "tripple" und "Double". Weiß nicht ob ich da der einzige mit der Meinung bin :D Aber ich schau Ma mach apks mit callern ;)

So, hat lange gedauert, sorry.

Das ist ein guter Einwand. im nächsten Release wird es genauso sein.

Also ..

- CALL_EVERY_DART_SINGLE_FILES (-ESF) => fliegt raus

- CALL_EVERY_DART (-E) wird geändert => anstatt gültige Werte 0 oder 1, kann 0, 1 oder 2 angegeben werden

  - 0 = Kein Calling für einzelne Darts => Standart
  - 1 = ist davon auszugehen, das der Benutzer den Score des Wurfs hören möchte. Sprich Number * Multiplikator
  - 2 = ist davon auszugehen, das die Audio-Dateien keine gesprochene Sprache enthält, sondern zum Beispiel einen Sirenen-Sound bei T20 -> fallback: triple (als Beispiel)


Der Gesamtscore wird dann ausgerufen, wenn folgendes vorliegt:
CALL_EVERY_DART == 0 oder CALL_EVERY_DART  == 2

Top!

**Comment by lbormann** [comment]
done in 2.12.0
