### ISSUE TITLE
Initial download of Voice package fails

### ISSUE THREAD

**Issue by mama99de** [lbormann/autodarts-caller#5]
Initial download of Voice package fails

##
Voice-pack fetching failed!
0 voice-pack(s) found.
##

**Comment by lbormann** [comment]
> Initial download of Voice package fails
> 
> Voice-pack fetching failed! 0 voice-pack(s) found.

https://github.com/lbormann/autodarts-caller?tab=readme-ov-file#failed-to-process-voice-pack-x
